"""
...
"""
__all__ = ["admin_menu", "admin_keyboard"]

import mrhomebot.admin_handlers.admin_menu as admin_menu
from mrhomebot.admin_handlers.admin_menu import first_admin_keyboard as admin_keyboard
import mrhomebot.admin_handlers.add_teacher as add_teacher
import mrhomebot.admin_handlers.assign_teacher_to_group as assign_teacher_to_group
from mrhomebot.admin_handlers.add_student import _handle_add_student
import mrhomebot.admin_handlers.add_discipline as add_discipline
import mrhomebot.admin_handlers.add_students_group as add_students_group
import mrhomebot.admin_handlers.ban_student as ban_student
import mrhomebot.admin_handlers.unban_student as unban_student
import mrhomebot.admin_handlers.assign_teacher_to_discipline as assign_teacher_to_discipline
import mrhomebot.admin_handlers.delete_group as delete_group
import mrhomebot.admin_handlers.delete_student as delete_student
import mrhomebot.admin_handlers.delete_teacher as delete_teacher
import mrhomebot.admin_handlers.upload_tests as upload_tests
import mrhomebot.admin_handlers.upload_start_configuration as upload_start_configuration
import mrhomebot.admin_handlers.download_all_test_and_answer as download_all_test_and_answer
import mrhomebot.admin_handlers.download_answers as download_answers
import mrhomebot.admin_handlers.download_full_report as download_full_report
import mrhomebot.admin_handlers.download_short_report as download_short_report
import mrhomebot.admin_handlers.download_finish_report as download_finish_report
import mrhomebot.admin_handlers.common_download_report_callback as common_download_report_callback
